Algoritmo "Exercicio3LacoParaManzano"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros.
// Autor(a)    : Raphael Alves
// Data atual  : 04/04/2022
Var
   // Seção de Declarações das variáveis
   contadora,soma:inteiro

Inicio
   // Seção de Comandos
para contadora de 1 ate 100 passo 1 faca
soma<- soma+contadora

fimpara
escreval(soma)

fimalgoritmo