Algoritmo "ExercicioLacoParaManzano1"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Apresentar resultado de 15 a 200 ao quadrado
// Autor(a)    : Raphael Alves
// Data atual  : 04/04/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos
   para contadora de 15 ate 200 passo 1 faca
      escreval(contadora,"² = ",contadora*contadora)
   fimpara


fimalgoritmo