Algoritmo "exercício 12"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Converssão de °F para °C.
// Autor(a)    : Raphael Alves
// Data atual  : 21/03/2022
Var
// Seção de Declarações das variáveis 
f: real
c:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite os graus Fahrenheit: ")
leia(f)
c<-5*(f-32)/9
escreval(c,"°C")


Fimalgoritmo