Algoritmo "LacoRepeticaoPara"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros.
// Autor(a)    : Raphael Alves
// Data atual  : 04/04/2022
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos
   para contadora de 0 ate 100 passo 10 faca
   escreval(contadora)
   fimpara


fimalgoritmo